# -*- coding: utf-8 -*-
"""06.06 Exercícios String.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tKRJ7IEmMke0hfwmm7fHG3TGMsodwv2z

# Exercícios

## 1. Cadastro de CPF

Crie um programa para cadastro de CPF de clientes que recebe o CPF em um input box apenas com números.

Ex: 'Insira seu CPF (digite apenas números)'

Caso o usuário digite algo diferente de números ou digite menos de 11 caracteres (tamanho do CPF brasileiro), o programa deve exibir uma mensagem de "Digite seu CPF corretamente e digite apenas números"
"""
# Resposta:
'''
cpf = input('Digite seu CPF: ')
chances = 1

while chances <= 3:
    if (len(cpf) == 11 and cpf.isnumeric()):
        print('\nCPF digitado corretamente! CPF:', cpf)
        break
    else:
        print ('\nCPF digitado é invalido. O CPF deve ter 11 NÚMEROS!')
        cpf  = input('Digite seu CPF: ')
        if chances == 3:
            print('\nSuas chances acabaram!\n')
        chances += 1'''


"""## 2. Melhorando nosso Cadastro de CPF

Agora, além das validações anteriores, vamos criar um input que permita que o usuário insira pontos, traços e inclusive espaços vazios.

Nosso programa deve "tratar" o que o usuário inserir para padronizar o CPF dele em apenas números.

A verificação de tamanho do CPF com 11 caracteres continua válida, mas ela só deve ser feita depois de retirar todos os pontos, traços e espaços do CPF que o cliente inserir e, uma vez retirados pontos, traços e espaços, devem sobrar apenas números no CPF. Qualquer outro caractere deve ser considerado inválido.

No final, nosso programa deve exibir uma mensagem para o usuário, caso ele tenha inserido o CPF inválido ou então apenas deve printar o CPF correto já só com número.
"""
# Reposta:

cpf = input('digite seu CPF: ')

#Retira os espaços.
cpf = cpf.strip() #verificar a real necessidade do uso do metodo. pois para remover todos os espaços, é necessa´rio usar o ultimo replace que retira inclusive os espaços entre os números e não somente os do inicio e fim, como faz o método em questão.
#retira os pontos
cpf = cpf.replace('.','')
#retira os traços
cpf = cpf.replace('-', '')
#retira as vírgulas
cpf = cpf.replace(',', '')
#retira os espaços
cpf = cpf.replace(' ', '')

chances = 1

while chances <= 3:
    if (len(cpf) == 11 and cpf.isnumeric()):
        print('\nCPF digitado corretamente! CPF:', cpf)
        break
    else:
        print ('\nCPF digitado é invalido. O CPF deve ter 11 NÚMEROS!')
        print(cpf)
        cpf  = input('Digite seu CPF: ')
        if chances == 3:
            print('\nSuas chances acabaram!\n')
        chances += 1  

"""## 3. Cadastro de e-mails

- A Hashtag sempre se comunica com seus clientes por e-mail. Para isso, a gente tem em cada página um cadastro de nome e e-mail. Nesse cadastro, nosso sistema verifica se o e-mail que a pessoa inseriu é um e-mail válido, verificando se ele tem '@' e se depois do '@' tem algum ponto, afinal:

- liragmail.com NÃO é um e-mail válido
- lira@gmail NÃO é um e-mail válido
- lira@gmail.com é um e-mail válido

Crie um programa que permita o cadastro de nome e e-mail de uma pessoa (por meio de inputs) e que verifique:
1. Se nome e e-mail foram preenchidos, caso contrário ele deve avisar para preencher todos os dados corretamente
2. Se o e-mail contém '@' e se depois do '@' existe algum '.', caso contrário ele deve exibir uma mensagem de e-mail inválido

Obs: Pode te ajudar lembrar do método .find da aula de Métodos de String. Você pode testar o que ele dá como resposta caso ele não encontre um item dentro da string
"""

