# -*- coding: utf-8 -*-
"""07.07.02 Exercícios Listas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BA-7w6uZza1l-gkiU_nn-K0VJ6n-aoFQ

# Exercícios

## 1. Faturamento do Melhor e do Pior Mês do Ano

Qual foi o valor de vendas do melhor mês do Ano?
E valor do pior mês do ano?
"""

meses = ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez']
vendas_1sem = [25000, 29000, 22200, 17750, 15870, 19900]
vendas_2sem = [19850, 20120, 17540, 15555, 49051, 9650]
vendas_ano = vendas_1sem + vendas_2sem
print("Vendas/Mês")
for i in range(len(vendas_ano)):
    print ("{} - {}".format(meses[i],vendas_ano[i]))

mais_vendas = max(vendas_ano)
menos_vendas = min(vendas_ano)

melhor_mes = vendas_ano.index(mais_vendas)
pior_mes = vendas_ano.index(menos_vendas)


print("\nO mês com maior número de vendas foi: {} com {} vendas".format(meses[melhor_mes],mais_vendas))
print("\nO mês com menor número de vendas foi: {} com {} vendas".format(meses[pior_mes],menos_vendas))


"""## 2. Continuação

Agora relacione as duas listas para printar 'O melhor mês do ano foi {} com {} vendas' e o mesmo para o pior mês do ano.

Calcule também o faturamento total do Ano e quanto que o melhor mês representou do faturamento total.

Obs: Para o faturamento total, pode usar a função sum(lista) que soma todos os itens de uma lista
"""

total_de_vendas_ano = sum(vendas_ano)
porcentagem_melhor_mes = (mais_vendas * 100)/total_de_vendas_ano
print("\nO total de vendas no ano, foi de: {}".format(total_de_vendas_ano))
print("\nPortanto o melhor mês em vendas, que foi {} com {} vendas, que representa {:.2f}% do total de vendas".format(meses[melhor_mes],mais_vendas,porcentagem_melhor_mes))



"""## 3. Crie uma lista com o top 3 valores de vendas do ano (sem fazer "no olho")

Dica: o método remove retira um item da lista.
"""

top3 = vendas_ano

while len(top3) > 3:
    top3.remove(min(top3))




